// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lwvijcdvemceqynquaoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3dmlqY2R2ZW1jZXF5bnF1YW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzEyMjIsImV4cCI6MjA3MDQwNzIyMn0.7VHKSrpO-x5eaj2U7uy74AotxMcsMjqvWZWFXqhAmXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);